// randomcodingquestion.com — page logic.
// Problems come from problems.js (generated by build/build.py).
const App = (() => {
  const PROBLEMS = window.PROBLEMS;
  const $ = id => document.getElementById(id);
  const esc = s => String(s).replace(/[&<>]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));
  const key = p => `${p.track}/${p.id}`;

  const drafts = {}; // code per problem during this visit
  let current = null, monaco = null, editor = null;

  // ---------- formatting ----------
  // A JS value printed the way Python would.
  const py = v =>
    v === true ? "True" : v === false ? "False" : v == null ? "None" :
    Array.isArray(v) ? "[" + v.map(py).join(", ") + "]" :
    typeof v === "string" ? JSON.stringify(v) : String(v);
  const pyRet = (v, p) => (p.spec.ret === "float" && Number.isInteger(v) ? v.toFixed(1) : py(v));

  // Verilog values: binary up to 8 bits, hex above, "x" for don't care.
  const bits = (v, w) =>
    v == null ? "x" : w === 1 ? String(v) : w <= 8 ? v.toString(2).padStart(w, "0") :
    "0x" + v.toString(16).padStart(Math.ceil(w / 4), "0");

  // Plain-text table with padded columns and a divider before column `sep`.
  function table(head, rows, sep) {
    const all = [head, ...rows];
    const w = head.map((_, i) => Math.max(...all.map(r => String(r[i]).length)));
    const line = r => r.map((c, i) => (i === sep ? "│ " : "") + String(c).padEnd(w[i])).join("  ").trimEnd();
    return all.map(line).join("\n");
  }

  // Normalise answers where order doesn't matter.
  function norm(v, cmp) {
    const k = x => JSON.stringify(x);
    const sort = a => [...a].sort((x, y) => (k(x) < k(y) ? -1 : k(x) > k(y) ? 1 : 0));
    if (cmp === "any" && Array.isArray(v)) return sort(v);
    if (cmp === "anyDeep" && Array.isArray(v)) return sort(v.map(x => (Array.isArray(x) ? sort(x) : x)));
    return v;
  }

  // ---------- problems ----------
  const pool = () => PROBLEMS.filter(p => p.track === $("track").value && ($("diff").value === "all" || p.diff === $("diff").value));
  const vIns = p => p.ports.filter(q => q.dir === "in" && q.name !== "clk");
  const vOuts = p => p.ports.filter(q => q.dir === "out");

  function examplesHTML(p) {
    if (p.track === "v") return verilogExamples(p);
    return p.tests.slice(0, p.examples).map(t => {
      if (p.kind === "design") {
        const [ops, args] = t.in;
        return `<pre>Input:  ${esc(py(ops))}\n        ${esc(py(args))}\nOutput: ${esc(py(t.out))}</pre>`;
      }
      const input = p.spec.params.map(([n], i) => `${n} = ${py(t.in[i])}`).join(", ");
      return `<pre>Input:  ${esc(input)}\nOutput: ${esc(pyRet(t.out, p))}</pre>`;
    }).join("");
  }

  function verilogExamples(p) {
    const ins = vIns(p), outs = vOuts(p);
    const head = [...ins.map(q => q.name), ...outs.map(q => q.name)];
    if (!p.seq) {
      const n = p.tests.length, k = Math.min(6, n);
      const rows = Array.from({ length: k }, (_, i) => p.tests[Math.floor(i * (n - 1) / Math.max(k - 1, 1))])
        .map(t => [...t.in.map((v, i) => bits(v, ins[i].width)), ...t.out.map((v, i) => bits(v, outs[i].width))]);
      return `<p>Examples:</p><pre>${esc(table(head, rows, ins.length))}</pre>`;
    }
    // Show at least 12 edges, extended so that some output change is visible.
    const s = p.tests[0], outAt = c => JSON.stringify(s.out[c]);
    let change = 3;
    while (change < s.out.length && outAt(change) === outAt(change - 1)) change++;
    const end = Math.min(Math.max(12, change + 4), 24, s.in.length);
    const rows = s.in.slice(0, end).map((inp, c) =>
      [c + 1, ...inp.map((v, i) => bits(v, ins[i].width)), ...s.out[c].map((v, i) => bits(v, outs[i].width))]);
    return `<p>Example (inputs applied before each rising edge, outputs right after it):</p><pre>${esc(table(["edge", ...head], rows, ins.length + 1))}</pre>`;
  }

  function verilogStarter(p) {
    const w = Math.max(...p.ports.map(q => (q.width > 1 ? `[${q.width - 1}:0] `.length : 0)));
    const lines = p.ports.map(q => {
      const range = q.width > 1 ? `[${q.width - 1}:0] ` : "";
      return `    ${q.dir === "in" ? "input " : "output"} logic ${range.padEnd(w)}${q.name}`;
    });
    return `module top_module (\n${lines.join(",\n")}\n);\n\n    \n\nendmodule\n`;
  }

  const starter = p => (p.track === "lc" ? p.starter : verilogStarter(p));

  function verilogLang() {
    const ids = monaco.languages.getLanguages().map(l => l.id);
    return ids.includes("systemverilog") ? "systemverilog" : ids.includes("verilog") ? "verilog" : "plaintext";
  }

  function loadIntoEditor(p) {
    if (!editor) return;
    monaco.editor.setModelLanguage(editor.getModel(), p.track === "lc" ? "python" : verilogLang());
    editor.setValue(drafts[key(p)] ?? starter(p));
    const lines = editor.getValue().split("\n");
    let ln = lines.findIndex((l, i) => i > 0 && /^\s+$/.test(l)); // first blank indented line
    if (ln < 0) ln = lines.length - 1;
    editor.setPosition({ lineNumber: ln + 1, column: lines[ln].length + 1 });
  }

  function show(p) {
    if (current && editor) drafts[key(current)] = editor.getValue();
    current = p;
    $("track").value = p.track;
    window.history.replaceState(null, "", "#" + key(p));
    $("title").textContent = `${p.title} (${p.diff})`;
    $("desc").innerHTML = p.desc + examplesHTML(p);
    $("out").innerHTML = "";
    delete $("out").dataset.showing;
    $("complexity").hidden = p.track !== "lc"; // Big-O only applies to the Python questions
    if (p.track === "v") Verilog.start();
    loadIntoEditor(p);
  }

  function scramble() {
    const list = pool();
    let next;
    do { next = list[Math.floor(Math.random() * list.length)]; } while (list.length > 1 && next === current);
    show(next);
  }

  // ---------- Python (Pyodide in a Web Worker) ----------
  const Python = (() => {
    const HARNESS_URL = new URL("harness.py?v=9", location.href).href;
    const SRC = `
      importScripts("https://cdn.jsdelivr.net/pyodide/v0.26.4/full/pyodide.js");
      const ready = (async () => {
        const [py, src] = await Promise.all([loadPyodide(), fetch(${JSON.stringify(HARNESS_URL)}).then(r => r.text())]);
        py.FS.writeFile("harness.py", src);
        py.runPython("import harness");
        postMessage({ ready: true });
        return py;
      })();
      onmessage = async e => {
        const py = await ready;
        const { code, spec, cases } = e.data;
        try { postMessage(JSON.parse(py.runPython("harness.run")(code, JSON.stringify(spec), JSON.stringify(cases)))); }
        catch (err) { postMessage({ error: String(err) }); }
      };`;
    let worker, ready = false, waiters = [];
    function start() {
      ready = false;
      worker = new Worker(URL.createObjectURL(new Blob([SRC], { type: "text/javascript" })));
      worker.addEventListener("message", e => { if (e.data.ready) { ready = true; waiters.splice(0).forEach(f => f()); } });
    }
    start();
    return {
      isReady: () => ready,
      async run(code, spec, cases, timeoutMs = 5000) {
        if (!ready) await new Promise(r => waiters.push(r));
        const w = worker;
        return new Promise(resolve => {
          const timer = setTimeout(() => { w.terminate(); start(); resolve({ timeout: true }); }, timeoutMs);
          w.onmessage = e => { if (e.data.ready) return; clearTimeout(timer); resolve(e.data); };
          w.postMessage({ code, spec, cases });
        });
      },
    };
  })();

  async function checkPython(p, code, status) {
    status(Python.isReady() ? "Running..." : "Loading Python...");
    const res = await Python.run(code, p.spec, p.tests.map(t => t.in));
    if (res.timeout) return "Time limit exceeded (5s). Infinite loop?";
    if (res.error) return esc(res.error);
    let pass = 0;
    const lines = res.results.map((r, i) => {
      const t = p.tests[i];
      const got = r.error ? null : JSON.parse(r.got);
      const ok = !r.error && JSON.stringify(norm(got, p.cmp)) === JSON.stringify(norm(t.out, p.cmp));
      if (ok) pass++;
      const input = p.kind === "design"
        ? py(t.in[0])
        : p.spec.params.map(([n], j) => `${n} = ${py(t.in[j])}`).join(", ");
      const short = input.length > 140 ? input.slice(0, 140) + "…" : input;
      return ok
        ? `✓ ${esc(short)}`
        : `✗ ${esc(short)}\n    expected ${esc(pyRet(t.out, p))}\n    got      ${esc(r.error ?? pyRet(got, p))}`;
    });
    const total = p.tests.length;
    const head = pass === total ? `<b>Accepted.</b> ${pass}/${total} tests passed.` : `<b>${pass}/${total} tests passed.</b>`;
    const printed = res.stdout ? `\n\nstdout:\n${esc(res.stdout)}` : "";
    return head + "\n\n" + lines.join("\n") + printed;
  }

  // ---------- Verilog ----------
  async function checkVerilog(p, code, status) {
    status(Verilog.isReady() ? "Synthesizing..." : "Loading Yosys (first time only, ~12 MB)...");
    const res = await Verilog.compile(code);
    if (res.error) return esc(res.error);
    const ins = vIns(p), outs = vOuts(p), outNames = outs.map(q => q.name);
    const mkSim = () => new Verilog.Sim(res.netlist, p.ports);
    try { mkSim(); } catch (e) { return esc(e.message); }
    const warn = res.warnings ? `\n\nyosys:\n${esc(res.warnings)}` : "";
    const same = (want, got) => want.every((v, i) => v == null || v === got[i]);
    const inObj = vals => Object.fromEntries(ins.map((q, i) => [q.name, vals[i]]));

    if (!p.seq) {
      const sim = mkSim(), fails = [];
      let pass = 0;
      for (const t of p.tests) {
        const got = sim.comb(inObj(t.in), outNames);
        if (same(t.out, got)) pass++;
        else fails.push([...t.in.map((v, i) => bits(v, ins[i].width)),
                         ...outs.map((q, i) => `${bits(t.out[i], q.width)}${t.out[i] == null || t.out[i] === got[i] ? "" : " ≠ " + bits(got[i], q.width)}`)]);
      }
      const total = p.tests.length;
      if (pass === total) return `<b>Accepted.</b> All ${total} input vectors match.${warn}`;
      const head = [...ins.map(q => q.name), ...outs.map(q => q.name)];
      return `<b>${pass}/${total} input vectors match.</b> First mismatches (expected ≠ got):\n<pre>${esc(table(head, fails.slice(0, 8), ins.length))}</pre>${warn}`;
    }

    let pass = 0, report = "";
    p.tests.forEach((s, si) => {
      const sim = mkSim();
      let bad = -1;
      const gots = [];
      for (let c = 0; c < s.in.length; c++) {
        const got = sim.cycle(inObj(s.in[c]), outNames);
        gots.push(got);
        if (!same(s.out[c], got)) { bad = c; break; }
      }
      if (bad < 0) { pass++; return; }
      if (report) return; // show only the first failing sequence
      const from = Math.max(0, bad - 7);
      const rows = [];
      for (let c = from; c <= bad; c++) {
        rows.push([(c === bad ? "✗ " : "  ") + (c + 1),
          ...s.in[c].map((v, i) => bits(v, ins[i].width)),
          ...outs.map((q, i) => bits(s.out[c][i], q.width)),
          ...outs.map((q, i) => bits(gots[c][i], q.width))]);
      }
      const head = ["edge", ...ins.map(q => q.name), ...outs.map(q => "exp " + q.name), ...outs.map(q => "got " + q.name)];
      report = `Test ${si + 1} fails after rising edge ${bad + 1}${from > 0 ? ` (showing edges ${from + 1}–${bad + 1})` : ""}:\n` +
               `<pre>${esc(table(head, rows, ins.length + 1))}</pre>`;
    });
    const total = p.tests.length, cycles = p.tests.reduce((a, s) => a + s.in.length, 0);
    if (pass === total) return `<b>Accepted.</b> ${total}/${total} test sequences (${cycles} clock cycles) match.${warn}`;
    return `<b>${pass}/${total} test sequences pass.</b> ${report}${warn}`;
  }

  async function check() {
    const btn = $("check");
    if (btn.disabled || !editor) return;
    btn.disabled = true;
    const p = current, code = editor.getValue(), out = $("out");
    delete out.dataset.showing;
    const status = text => { out.textContent = text; };
    let html;
    try {
      html = p.track === "lc" ? await checkPython(p, code, status) : await checkVerilog(p, code, status);
    } catch (e) {
      html = esc(e.message || e);
    }
    btn.disabled = false;
    if (current === p) out.innerHTML = html;
  }

  // ---------- boot ----------
  function fromHash() {
    const h = decodeURIComponent(location.hash.slice(1));
    const [t, id] = h.includes("/") ? h.split("/") : ["lc", h];
    return PROBLEMS.find(p => p.track === t && p.id === id);
  }

  $("scramble").onclick = scramble;
  $("check").onclick = check;
  // Complexity toggles: a second click hides it again.
  $("complexity").onclick = () => {
    const out = $("out");
    if (out.dataset.showing === "complexity") { out.innerHTML = ""; delete out.dataset.showing; return; }
    const c = current.complexity;
    out.innerHTML = `<b>Target complexity:</b> Time ${esc(c.time)} · Space ${esc(c.space)}` +
                    (c.note ? ` (${esc(c.note)})` : "");
    out.dataset.showing = "complexity";
  };
  $("track").onchange = scramble;
  $("diff").onchange = () => { if (!pool().includes(current)) scramble(); };
  window.addEventListener("hashchange", () => { const p = fromHash(); if (p && p !== current) show(p); });
  const initial = fromHash();
  initial ? show(initial) : scramble();

  return {
    attachEditor(m) {
      monaco = m;
      editor = monaco.editor.create($("editor"), {
        value: starter(current), language: current.track === "lc" ? "python" : verilogLang(),
        minimap: { enabled: false }, scrollBeyondLastLine: false, automaticLayout: true,
        tabSize: 4, insertSpaces: true,
      });
      editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter, check);
      loadIntoEditor(current);
    },
  };
})();
