// Shapes of the data in problems.js (generated by build/build.py),
// the messages exchanged with the workers, and the bits of Monaco we use.

export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export type Track = "lc" | "v" | "fin";
export type Difficulty = "easy" | "medium" | "hard";
export type Category = "technical" | "markets" | "brainteaser";

interface ProblemBase {
  id: string;
  title: string;
  topic: string;
  desc: string; // HTML
}

// ---------- Python (LeetCode-style) ----------

export interface PySpec {
  kind: "fn" | "design";
  fn: string | null;
  cls: string | null;
  params: [name: string, type: string][] | null;
  ret: string | null;
  inplace: number | null;
}

export interface PyProblem extends ProblemBase {
  track: "lc";
  diff: Difficulty;
  kind: "fn" | "design";
  cmp: "exact" | "any" | "anyDeep"; // "any": order of the returned list doesn't matter
  examples: number;
  starter: string;
  spec: PySpec;
  tests: { in: Json[]; out: Json }[];
  complexity: { time: string; space: string; note: string };
}

// ---------- Verilog ----------

export interface Port {
  name: string;
  dir: "in" | "out";
  width: number;
}

/** An expected output value; null means "don't care". */
export type Expected = number | null;

interface VerilogBase extends ProblemBase {
  track: "v";
  diff: Difficulty;
  kind: "verilog";
  ports: Port[];
}

export interface CombProblem extends VerilogBase {
  seq: false;
  tests: { in: number[]; out: Expected[] }[]; // one input vector each
}

export interface SeqProblem extends VerilogBase {
  seq: true;
  tests: { in: number[][]; out: Expected[][] }[]; // one clock cycle per row
}

export type VerilogProblem = CombProblem | SeqProblem;

// ---------- Finance ----------

export type FinanceAnswer =
  | { type: "open" } // no single answer: Check shows key points
  | { type: "number"; value: number; unit: "" | "$" | "$m" | "%" | "x"; tol: number } // tol is relative
  | { type: "choice"; options: string[]; correct: string }
  | { type: "expr"; numbers: number[]; target: number; reference: string };

export interface FinanceProblem extends ProblemBase {
  track: "fin";
  kind: "finance";
  diff: Category;
  answer: FinanceAnswer;
  key: string[]; // key points (open questions)
  explain: string[]; // worked solution (number, choice, expr)
}

export type Problem = PyProblem | VerilogProblem | FinanceProblem;

// ---------- Yosys JSON netlist (only what the simulator reads) ----------

export type Bit = number | "0" | "1" | "x" | "z";

export interface Netlist {
  ports: Record<string, { direction: "input" | "output" | "inout"; bits: Bit[] }>;
  cells: Record<string, { type: string; connections: Record<string, Bit[]> }>;
}

// ---------- worker messages ----------

export interface PyCaseResult { got?: string; error?: string }
export type PyResponse =
  | { ready: true }
  | { error: string }
  | { results: PyCaseResult[]; stdout: string };

export type YosysResponse =
  | { ready: true }
  | { fatal: string }
  | { json: string; log: string }
  | { failed: true; log: string };

declare global {
  interface Window {
    PROBLEMS: Problem[];
  }
  /** Version stamp injected by build.mjs, used to bust browser caches. */
  const __VERSION__: string;
}
